# Snipe-IT Docker Compose for Render Deployment
# This file is optimized for Render's infrastructure

version: '3.8'

services:
  app:
    image: snipe/snipe-it:latest
    restart: unless-stopped
    ports:
      - "10000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - APP_TIMEZONE=${APP_TIMEZONE:-UTC}
      - APP_LOCALE=${APP_LOCALE:-en}
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-Snipe-IT}
      - IMAGE_LIB=gd
      - SESSION_LIFETIME=${SESSION_LIFETIME:-12000}
      - EXPIRE_ON_CLOSE=${EXPIRE_ON_CLOSE:-false}
      - ENCRYPT=${ENCRYPT:-false}
      - COOKIE_NAME=snipeit_session
      - SECURE_COOKIES=${SECURE_COOKIES:-true}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
      - FILESYSTEM_DISK=local
      - LOG_CHANNEL=stack
      - LOG_LEVEL=${LOG_LEVEL:-warning}
      - SESSION_SECURE_COOKIE=${SESSION_SECURE_COOKIE:-true}
      - SESSION_HTTP_ONLY=${SESSION_HTTP_ONLY:-true}
    volumes:
      - storage:/var/lib/snipeit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  storage: 