services:
  - type: web
    name: snipe-it
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_LOCALE
        value: en
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: snipe-it-db
          type: pserv
          property: host
      - key: DB_PORT
        fromService:
          name: snipe-it-db
          type: pserv
          property: port
      - key: DB_DATABASE
        fromService:
          name: snipe-it-db
          type: pserv
          property: database
      - key: DB_USERNAME
        fromService:
          name: snipe-it-db
          type: pserv
          property: username
      - key: DB_PASSWORD
        fromService:
          name: snipe-it-db
          type: pserv
          property: password
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: Snipe-IT
      - key: IMAGE_LIB
        value: gd
      - key: SESSION_LIFETIME
        value: 12000
      - key: EXPIRE_ON_CLOSE
        value: false
      - key: ENCRYPT
        value: false
      - key: COOKIE_NAME
        value: snipeit_session
      - key: SECURE_COOKIES
        value: true
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_DRIVER
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: warning
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_HTTP_ONLY
        value: true

  - type: pserv
    name: snipe-it-db
    env: docker
    plan: starter
    region: oregon
    dockerImage: mariadb:11.4.7
    dockerCommand: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    envVars:
      - key: MYSQL_DATABASE
        value: snipeit
      - key: MYSQL_USER
        value: snipeit
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true 